{{/*
################################################################################
#   Copyright (c) 2019,2020 AT&T Intellectual Property.                        #
#   Copyright (c) 2019 Nokia.                                                  #
#   Copyright (C) 2023 hyphenOs Software Labs.
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################
*/}}
{{- define "ves.dmaap.config.cm.name" -}}
  {{- $name := ( include "common.name.ves" . ) -}}
  {{- printf "%s-dmaap-config" $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- define "ves.collector.properties.cm.name" -}}
  {{- $name := ( include "common.name.ves" . ) -}}
  {{- printf "%s-collector-properties" $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ves.dmaap.config.cm.name" . }}
data:
  ves-dmaap-config.json: |
    {
      "ves-syslog": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-statechange": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-thresholdCrossingAlert": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-heartbeat": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_HEARTBEAT_OUTPUT/"
        }
      },
      "ves-other": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_OTHER_OUTPUT/"
        }
      },
      "ves-mobileflow": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-sipsignaling": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-voicequality": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-fault": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_FAULT_OUTPUT/"
        }
      },
      "ves-measurement": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.VES_MEASUREMENT_OUTPUT/"
        }
      },
      "ves-3gpp-fault-supervision": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_3GPP_FAULTSUPERVISION_OUTPUT/"
        }
      },
      "ves-3gpp-provisioning": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_3GPP_PROVISIONING_OUTPUT/"
        }
      },
      "ves-3gpp-heartbeat": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_3GPP_HEARTBEAT_OUTPUT/"
        }
      },
      "ves-3gpp-performance-assurance": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_3GPP_PERFORMANCEASSURANCE_OUTPUT/"
        }
      },
      "ves-syslog-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-statechange-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-thresholdCrossingAlert-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-heartbeat-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-other-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-mobileflow-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-sipsignaling-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTSves7_valid_ip_v4.json-DEV"
        }
      },
      "ves-voicequality-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-fault-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-measurement-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-3gpp-fault-supervision-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_3GPP_FAULTSUPERVISION_OUTPUT"
        }
      },
      "ves-3gpp-provisioning-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.SEC_3GPP_FAULTSUPERVISION_OUTPUT"
        }
      },
      "ves-3gpp-heartbeat-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-3gpp-performance-assurance-secondary": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/DCAE-SE-COLLECTOR-EVENTS-DEV"
        }
      },
      "ves-pnfRegistration": {
        "type": "message_router",
        "dmaap_info": {
          "location": "mtl5",
          "topic_url": "http://onap-dmaap:3904/events/unauthenticated.VES_PNFREG_OUTPUT/"
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ves.collector.properties.cm.name" . }}
data:
  {{- (.Files.Glob "resources/*").AsConfig | nindent 2 }}
