apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.ingressname.ves" . }}
  annotations:
    "konghq.com/strip-path": "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: {{ include "common.kongpath.aux.vescollector" . }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "common.servicename.ves.http" . }}
            port:
              number: {{ include "common.serviceport.ves.http" . }}
